# Generated by Django 4.2.6 on 2023-11-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='final_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Final Profit'),
            preserve_default=False,
        ),
    ]
