# Generated by Django 4.2.6 on 2023-10-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_investment_entrepreneur'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='income',
            field=models.FloatField(default=0),
        ),
    ]
