# Generated by Django 4.2.6 on 2023-11-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_investment_final_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
