# Generated by Django 4.2.6 on 2023-11-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_investment_is_submitted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ('-pk',)},
        ),
    ]
