# Generated by Django 4.2.6 on 2023-11-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userbalance_user'),
        ('investment', '0004_alter_investment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_want_to_send_to_cart', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_want_to_keep_in_the_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_want_to_send_to_charity_fund', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_want_to_send_to_debt_fund', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_report', to='investment.investment')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_report', to='account.investor')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
