# Generated by Django 4.2.6 on 2023-12-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_investmentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='amount_deducated_from_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investment',
            name='amount_must_send',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
