# Generated by Django 4.2.6 on 2023-12-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_alter_investment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ('investor__user__first_name',)},
        ),
        migrations.AlterModelOptions(
            name='investmentreport',
            options={'ordering': ('investor__user__first_name',)},
        ),
    ]
