# Generated by Django 4.2.6 on 2023-12-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0008_alter_investment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentreport',
            name='is_amount_sended_to_investor',
            field=models.BooleanField(default=False),
        ),
    ]
