# Generated by Django 4.2.6 on 2023-12-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0009_investmentreport_is_amount_sended_to_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_amount_sended',
            field=models.BooleanField(default=False),
        ),
    ]
