# Generated by Django 4.2.6 on 2023-12-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0010_investment_is_amount_sended'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_amount_sended_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
