# Generated by Django 4.2.6 on 2023-12-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0011_investment_is_amount_sended_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='amount_from_debt_fund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='investment',
            name='is_from_debt_fund',
            field=models.BooleanField(default=False),
        ),
    ]
