# Generated by Django 4.2.6 on 2024-01-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0012_investment_amount_from_debt_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount_from_debt_fund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
