# Generated by Django 4.2.6 on 2023-11-21 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_education_user_alter_experience_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='investor/profile_pictures/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])], verbose_name='Profile Picture'),
        ),
    ]
