# Generated by Django 4.2.5 on 2023-09-20 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_investor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='referances',
            field=models.ManyToManyField(blank=True, related_name='investors', to=settings.AUTH_USER_MODEL, verbose_name='Referances'),
        ),
    ]
