# Generated by Django 4.2.5 on 2023-09-21 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_investor_referances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='referances',
        ),
        migrations.AddField(
            model_name='investor',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='investors', to=settings.AUTH_USER_MODEL, verbose_name='References'),
        ),
    ]
