# Generated by Django 4.2.6 on 2023-11-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userbalance_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_fund', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('charity_fund', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
