# Generated by Django 4.2.6 on 2023-12-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_investor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Phone number'),
        ),
    ]
