# Generated by Django 4.2.6 on 2024-01-01 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_investor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2024)], verbose_name='End Year'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2024)], verbose_name='Start Year'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2024)], verbose_name='end_year'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_year',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2024)], verbose_name='start_year'),
        ),
    ]
