# Generated by Django 4.2.6 on 2024-01-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_education_end_year_alter_education_start_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='debt_fund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
