# Generated by Django 4.2.6 on 2024-01-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userbalance_debt_fund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbalance',
            old_name='debt_fund',
            new_name='money_in_debt_fund',
        ),
    ]
