# Generated by Django 4.2.6 on 2023-10-30 11:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DebtFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Proyekt adı', max_length=255, verbose_name='Project name')),
                ('start_date', models.DateField(auto_now_add=True, help_text='Başlanğıc tarixi', verbose_name='Start date')),
                ('end_date', models.DateField(help_text='Bitmə tarixi', verbose_name='End date')),
                ('finished_date', models.DateField(help_text='Yekunlaşdığı tarix', verbose_name='Finished date')),
                ('description', models.TextField(help_text='Açıqlama')),
                ('entrepreneur_form', models.JSONField()),
                ('is_active', models.BooleanField(default=False)),
                ('count', models.IntegerField(blank=True, default=1)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, help_text='Alış qiyməti', max_digits=10, verbose_name='Purchase price')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, help_text='Satış qiyməti', max_digits=10, verbose_name='Sale price')),
                ('total_investment', models.DecimalField(decimal_places=2, default=0, help_text='Ümumi investisiya', max_digits=10, verbose_name='Total Investment')),
                ('gross_income', models.DecimalField(decimal_places=2, default=0, help_text='Ümumi gəlir', max_digits=10, verbose_name='Gross income')),
                ('platform_cost_percentage', models.PositiveIntegerField(default=2, help_text='Platforma xərci faizi', verbose_name='Platform cost percentage')),
                ('platform_cost', models.DecimalField(decimal_places=2, default=0, help_text='Platforma xərci', max_digits=10, verbose_name='Platform cost')),
                ('final_profit', models.DecimalField(decimal_places=2, default=0, help_text='Yekun Mənfəət', max_digits=10, verbose_name='Final profit')),
                ('investor_share_percentage', models.PositiveIntegerField(default=25, help_text='İnvestorun payı faizi', verbose_name='Investor share percentage')),
                ('investor_share', models.DecimalField(decimal_places=2, default=0, help_text='İnvestorun payı', max_digits=10, verbose_name='Investor share')),
                ('entrepreneur_share_percentage', models.PositiveIntegerField(default=63, help_text='Formaçının payı faizi', verbose_name='Entrepreneur share percentage')),
                ('entrepreneur_share', models.DecimalField(decimal_places=2, default=0, help_text='Formaçının payı', max_digits=10, verbose_name='Entrepreneur share')),
                ('debt_to_the_fund_percentage', models.PositiveIntegerField(default=5, help_text='Fonda borc faizi', verbose_name='Debt to the fund percentage')),
                ('debt_to_the_fund', models.DecimalField(decimal_places=2, default=0, help_text='Fonda borc', max_digits=10, verbose_name='Debt to the fund')),
                ('charity_to_the_fund_percentage', models.PositiveIntegerField(default=7, help_text='Fonda sədəqə faizi', verbose_name='Charity to the fund percentage')),
                ('charity_to_the_fund', models.DecimalField(decimal_places=2, default=0, help_text='Fonda sədəqə', max_digits=10, verbose_name='Charity to the fund')),
                ('profit_ratio', models.FloatField(default=0, help_text='Mənfəət əmsalı', verbose_name='Profit ratio')),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount collected')),
                ('owner', models.ForeignKey(help_text='Formaçı', on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneurs', to='account.investor')),
            ],
        ),
        migrations.CreateModel(
            name='EntrepreneurForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('questions', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='EntrepreneurImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='investor/entrepreneur_image/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])], verbose_name='Entrepreneur Image')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='entrepreneur.entrepreneur')),
            ],
        ),
    ]
