# Generated by Django 4.2.6 on 2023-10-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='finished_date',
            field=models.DateField(help_text='Yekunlaşdığı tarix', null=True, verbose_name='Finished date'),
        ),
    ]
