# Generated by Django 4.2.5 on 2023-10-01 03:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0002_entrepreneur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrepreneurform',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='amount_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount collected'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='entrepreneur_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrepreneur.entrepreneurform'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='project_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Project name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Target amount'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EntrepreneurImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='investor/entrepreneur_image/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])], verbose_name='Entrepreneur Image')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='entrepreneur.entrepreneur')),
            ],
        ),
    ]
