# Generated by Django 4.2.6 on 2023-10-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0002_alter_entrepreneur_finished_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='finished_date',
            field=models.DateField(blank=True, help_text='Yekunlaşdığı tarix', null=True, verbose_name='Finished date'),
        ),
    ]
