# Generated by Django 4.2.5 on 2023-10-01 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0003_rename_name_entrepreneurform_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='entrepreneur_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrepreneurs', to='entrepreneur.entrepreneurform'),
        ),
    ]
