# Generated by Django 4.2.6 on 2023-11-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0003_alter_entrepreneur_finished_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurCalculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='EntrepreneurForm',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='entrepreneur_form',
        ),
    ]
