# Generated by Django 4.2.6 on 2023-10-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0004_alter_entrepreneur_entrepreneur_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='income_interest',
            field=models.FloatField(default=0),
        ),
    ]
