# Generated by Django 4.2.6 on 2023-11-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0004_entrepreneurcalculate_delete_entrepreneurform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
