# Generated by Django 4.2.6 on 2023-11-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0005_entrepreneur_is_finished'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntrepreneurCalculate',
        ),
    ]
