# Generated by Django 4.2.6 on 2023-10-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0005_entrepreneur_income_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrepreneur',
            old_name='income_interest',
            new_name='income',
        ),
    ]
