# Generated by Django 4.2.6 on 2023-11-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0006_delete_entrepreneurcalculate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharityFund',
        ),
        migrations.DeleteModel(
            name='DebtFund',
        ),
    ]
