# Generated by Django 4.2.6 on 2023-12-17 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0008_alter_entrepreneurimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 12, 17), help_text='Başlanğıc tarixi', verbose_name='Start date'),
        ),
    ]
