# Generated by Django 4.2.6 on 2023-12-17 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0009_alter_entrepreneur_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Başlanğıc tarixi', verbose_name='Start date'),
        ),
    ]
