# Generated by Django 4.2.6 on 2024-01-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0010_alter_entrepreneur_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='charity_to_the_fund_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Fonda sədəqə faizi', verbose_name='Charity to the fund percentage'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='entrepreneur_share_percentage',
            field=models.PositiveIntegerField(default=65, help_text='Formaçının payı faizi', verbose_name='Entrepreneur share percentage'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='investor_share_percentage',
            field=models.PositiveIntegerField(default=30, help_text='İnvestorun payı faizi', verbose_name='Investor share percentage'),
        ),
    ]
