# Generated by Django 4.2.6 on 2024-02-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0011_alter_entrepreneur_charity_to_the_fund_percentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrepreneur',
            options={'ordering': ('-project_name',)},
        ),
    ]
