# Generated by Django 4.2.6 on 2024-02-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneur', '0012_alter_entrepreneur_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrepreneur',
            options={},
        ),
    ]
